### ISSUE TITLE
unixtimestamp

### ISSUE THREAD

**Issue by vinnitu** [wwwtyro/candygraph#24]
Hello!

Can you create example usage Candygraph with milliseconds timestamps (source is Date.now())?

**Comment by wwwtyro** [comment]
Yes, that's a good idea; I don't think there's an example showing how to deal with precision issues. It will look something like shifting the input values closer to one, then changing the labels so that they match the associated timestamps.  I'll try to get to it soon.

**Comment by wwwtyro** [comment]
Here's the example I promised you, sorry for the wait: https://github.com/wwwtyro/candygraph/blob/master/docs/examples/src/ex-01300-precision.ts

You can see it at the bottom here: https://wwwtyro.github.io/candygraph/examples/dist/

The approach was as described - shift the data closer to one and then update the labels appropriately. This was all done on the CPU, but we might be able to add a general offset parameter to the shaders so that this could happen on the GPU. @blubmin has experimented with this on linear scales to good effect; I'm going to try it out and see how it behaves with all the scales.

**Comment by skortchmark9** [comment]
Definitely interested in a general offset parameter - because I need to offset my timestamps on the CPU I can't see how to reuse them on the GPU.
